### ISSUE TITLE
1.4 missing files during install

### ISSUE THREAD

**Issue by BobbyD-FL** [justanr/marshmallow_enum#15]
Unable to install 1.4.  See error below, the file 'README.md' is missing and is not included in the tar.gz

```
$ pip install marshmallow-enum==1.4
Downloading/unpacking marshmallow-enum==1.4
  Downloading marshmallow-enum-1.4.tar.gz
  Running setup.py egg_info for package marshmallow-enum
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/jdorlus/dev/envs/project1/build/marshmallow-enum/setup.py", line 12, in <module>
        with open('README.md', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/jdorlus/dev/envs/project1/build/marshmallow-enum/setup.py", line 12, in <module>

    with open('README.md', 'r') as f:

IOError: [Errno 2] No such file or directory: 'README.md'
```

```
$ md5sum marshmallow-enum-1.4.tar.gz
8f49b0a02413170aefd035b523ffe9fa  marshmallow-enum-1.4.tar.gz
```

```
$ tar --gzip --list --verbose --file=marshmallow-enum-1.4.tar.gz
drwxrwxr-x  0 anr    anr         0 Aug 20 20:18 marshmallow-enum-1.4/
-rw-rw-r--  0 anr    anr       766 Aug 20 12:08 marshmallow-enum-1.4/setup.py
drwxrwxr-x  0 anr    anr         0 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum.egg-info/
-rw-rw-r--  0 anr    anr        17 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum.egg-info/top_level.txt
-rw-rw-r--  0 anr    anr         1 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum.egg-info/dependency_links.txt
-rw-rw-r--  0 anr    anr       246 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum.egg-info/SOURCES.txt
-rw-rw-r--  0 anr    anr        19 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum.egg-info/requires.txt
-rw-rw-r--  0 anr    anr      3015 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum.egg-info/PKG-INFO
drwxrwxr-x  0 anr    anr         0 Aug 20 20:18 marshmallow-enum-1.4/marshmallow_enum/
-rw-rw-r--  0 anr    anr      3402 Aug 20 20:08 marshmallow-enum-1.4/marshmallow_enum/__init__.py
-rw-rw-r--  0 anr    anr        67 Aug 20 20:18 marshmallow-enum-1.4/setup.cfg
-rw-rw-r--  0 anr    anr      3015 Aug 20 20:18 marshmallow-enum-1.4/PKG-INFO
```

**Comment by justanr** [comment]
argh, I tried packaging the README with it. Lemme get a fix out. I had a similar issue with flask-allows, changing my release process might have been a bad idea. Can you confirm if the wheel works?

**Comment by justanr** [comment]
Just pushed 1.4.1 with a corrected package data, if this issue persists, let me know and I'll fix it.
