### ISSUE TITLE
NameError: name 'EnumField' is not defined

### ISSUE THREAD

**Issue by flip111** [justanr/marshmallow_enum#20]
```python
# regular enum
class ImageType(Enum):
    small = 1
    big = 2

# sqlalchemy class
class Image(db.Model):
    __tablename__ = 'image'
    id = db.Column(db.Integer, primary_key=True)
    image_type = db.Column(db.Enum(ImageType))

# marshmallow schema
class ImageSchema(ma.ModelSchema):
    class Meta:
        model = Image  # <-- error on this line
    image_type = EnumField(ImageType)

image_schema = ImageSchema()
```

error: `NameError: name 'EnumField' is not defined`

is marshmallow_enum not compatible with the `Meta` class ?

**Comment by flip111** [comment]
Hhm i'm not sure how to reproduce this one .. maybe i should have copied my project. I changed code and now i get this error when i try to use this enum with marshmallow.

```

builtins.TypeError

TypeError: Object of type 'ImageType' is not JSON serializable
Traceback (most recent call last)

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__

    return self.wsgi_app(environ, start_response)

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app

    response = self.handle_exception(e)

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app

    response = self.full_dispatch_request()

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request

    rv = self.dispatch_request()

    File "venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "server/main.py", line 86, in index

    return render_template('index.html', data=data)

    File "venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template

    context, ctx.app)

    File "venv/lib/python3.6/site-packages/flask/templating.py", line 116, in _render

    rv = template.render(context)

    File "venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render

    return original_render(self, *args, **kwargs)

    File "venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render

    return self.environment.handle_exception(exc_info, True)

    File "venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise

    raise value.with_traceback(tb)

    File "server/templates/index.html", line 9, in top-level template code

    <script type="text/javascript">var data = {{data|tojson|safe}};</script>

    File "venv/lib/python3.6/site-packages/flask/json.py", line 269, in tojson_filter

    return Markup(htmlsafe_dumps(obj, **kwargs))

    File "venv/lib/python3.6/site-packages/flask/json.py", line 183, in htmlsafe_dumps

    rv = dumps(obj, **kwargs) \

    File "venv/lib/python3.6/site-packages/flask/json.py", line 123, in dumps

    rv = _json.dumps(obj, **kwargs)

    File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps

    **kw).encode(obj)

    File "/usr/lib/python3.6/json/encoder.py", line 199, in encode

    chunks = self.iterencode(o, _one_shot=True)

    File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode

    return _iterencode(o, 0)

    File "venv/lib/python3.6/site-packages/flask/json.py", line 80, in default

    return _json.JSONEncoder.default(self, o)

    File "/usr/lib/python3.6/json/encoder.py", line 180, in default

    o.__class__.__name__)

    TypeError: Object of type 'ImageType' is not JSON serializable

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

but i remember that on the stacktrace there were just 4 calls ... so before flask started loading anything.

**Comment by justanr** [comment]
That trace looks like Marshmallow either isn't being run or the result of the serializer isn't being passed into the JSON filter.

**Comment by justanr** [comment]
I'm going to close, but feel free to reopen if it turns out this library is causing the issue.
